name: service_worker
version: 0.0.7
author: Istvan Soos <istvan.soos@gmail.com>
description: Service Worker API

homepage: https://github.com/isoos/service_worker

environment:
  sdk: ">=1.19.0 <2.0.0"

dependencies:
  func: ^0.1.1
  js: ^0.6.1

