name: service_worker
version: 0.1.2
author: Istvan Soos <istvan.soos@gmail.com>
description: JavaScript bindings for the Service Worker API.

homepage: https://github.com/isoos/service_worker

environment:
  sdk: ">=1.21.0 <2.0.0"

dependencies:
  js: ^0.6.1
